apiVersion: v1
kind: Service
metadata:
  name: zero-downtime-app-service
spec:
  type: NodePort
  selector:
    app: zero-downtime-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
